import { NextResponse } from 'next/server';

const headers = { 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'no-store' };
const text = (value: unknown, max = 100000) => typeof value === 'string' ? value.slice(0, max) : '';
const escape = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));

// Public distribution contains generated article fields only, never account records.
export async function GET() {
    try {
        const response = await fetch('https://www.neonpeter.com/api/blog-auto/posts', { cache: 'no-store', signal: AbortSignal.timeout(15000) });
        if (!response.ok) throw new Error('Feed unavailable');
        const source: unknown = await response.json();
        if (!Array.isArray(source)) throw new Error('Invalid feed');
        const posts = source.filter(p => p && p.isAutoGenerated === true && typeof p.title === 'string').map(p => {
            const content = text(p.content);
            return { id: text(p.id, 200), title: text(p.title, 500), content, htmlContent: `<div>${escape(content).replace(/\n/g, '<br>')}</div>`, excerpt: text(p.excerpt, 1000), tags: Array.isArray(p.tags) ? p.tags.filter((t: unknown) => typeof t === 'string').slice(0, 30) : [], images: Array.isArray(p.images) ? p.images.filter((url: unknown) => typeof url === 'string' && /^https:\/\//.test(url)).slice(0, 30) : [], newsCategory: text(p.newsCategory, 100), createdAt: p.createdAt ?? null, isAutoGenerated: true };
        });
        return NextResponse.json({ success: true, posts }, { headers });
    } catch {
        return NextResponse.json({ success: false, posts: [], error: '자동생성 글 목록을 가져오지 못했습니다. 잠시 후 다시 시도해주세요.' }, { status: 502, headers });
    }
}
