'use client';
import { useState } from 'react';
import Link from 'next/link';
import { usePlatform } from '@/contexts/PlatformContext';
function key(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
export default function CalendarPage() {
    const { data, ready } = usePlatform();
    const [month, setMonth] = useState(() => new Date(2026, 9, 1));
    const [mode, setMode] = useState<'month' | 'list'>('month');
    const [category, setCategory] = useState('전체');
    const [personal, setPersonal] = useState(false);
    const [email, setEmail] = useState('');
    const courses = data.courses.filter(c => c.published && c.startDate.startsWith(key(month).slice(0, 7)) && (category === '전체' || c.category === category) && (!personal || data.enrollments.some(e => e.courseId === c.id && e.email === email.trim().toLowerCase() && !['반려', '환불'].includes(e.status)))).sort((a, b) => `${a.startDate}${a.startTime}`.localeCompare(`${b.startDate}${b.startTime}`));
    const start = new Date(month.getFullYear(), month.getMonth(), 1);
    start.setDate(start.getDate() - start.getDay());
    const days = Array.from({ length: 42 }, (_, i) => { const d = new Date(start); d.setDate(d.getDate() + i); return d; });
    const exportCalendar = () => { const events = courses.map(c => { const clean = (s: string) => s.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/,/g, '\\,').replace(/;/g, '\\;'); const stamp = (t: string) => c.startDate.replaceAll('-', '') + 'T' + t.replace(':', '') + '00'; return ['BEGIN:VEVENT', `UID:${c.id}@aiedu.local`, `DTSTAMP:${new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '')}`, `DTSTART;TZID=Asia/Seoul:${stamp(c.startTime)}`, `DTEND;TZID=Asia/Seoul:${stamp(c.endTime)}`, `SUMMARY:${clean(c.title)}`, `LOCATION:${clean(c.location)}`, 'END:VEVENT'].join('\r\n'); }); const url = URL.createObjectURL(new Blob([['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//AIEDU//KO', ...events, 'END:VCALENDAR'].join('\r\n')], { type: 'text/calendar;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'education-calendar.ics'; a.click(); URL.revokeObjectURL(url); };
    return <div className="space-y-5"><h1 className="text-2xl font-black">통합 교육 캘린더</h1><div className="flex flex-wrap items-center gap-3"><button aria-label="이전 달" className="rounded border p-2" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>←</button><strong>{month.getFullYear()}년 {month.getMonth() + 1}월</strong><button aria-label="다음 달" className="rounded border p-2" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>→</button><button className="rounded border p-2" onClick={() => setMonth(new Date())}>오늘</button><select aria-label="교육 분야" className="rounded border p-2" value={category} onChange={e => setCategory(e.target.value)}>{['전체', 'AI·데이터', '업무자동화', '개발·백엔드', '비즈니스·마케팅'].map(c => <option key={c}>{c}</option>)}</select><button className="rounded border p-2" onClick={() => setMode(mode === 'month' ? 'list' : 'month')}>{mode === 'month' ? '목록 보기' : '월간 보기'}</button><button className="rounded border p-2" onClick={exportCalendar}>일정 내보내기 (.ics)</button></div><label className="flex items-center gap-2"><input type="checkbox" checked={personal} onChange={e => { setPersonal(e.target.checked); setEmail(localStorage.getItem('platform-learner-email') ?? ''); }}/>내 신청 일정만 보기</label>{personal && <input aria-label="일정 조회 이메일" className="rounded border p-2" value={email} onChange={e => setEmail(e.target.value)} placeholder="신청 이메일"/>}
 {!ready ? <p>일정을 불러오는 중입니다.</p> : mode === 'month' ? <div className="overflow-x-auto rounded-xl border bg-white"><div className="min-w-[700px]"><div className="grid grid-cols-7 text-center">{['일', '월', '화', '수', '목', '금', '토'].map(d => <div className="border-b p-3 font-bold" key={d}>{d}</div>)}</div><div className="grid grid-cols-7">{days.map(d => <div className={`min-h-28 border-b border-r p-2 ${d.getMonth() !== month.getMonth() ? 'bg-slate-50 text-slate-400' : ''}`} key={key(d)}><span>{d.getDate()}</span>{courses.filter(c => c.startDate === key(d)).map(c => <Link key={c.id} className="mt-1 block rounded bg-blue-50 p-2 text-xs font-bold text-blue-700" href={`/courses/${c.id}`}>{c.startTime} {c.title}<span className="block font-normal">{c.remainingSeats > 0 ? `잔여 ${c.remainingSeats}석` : '모집 마감'}</span></Link>)}</div>)}</div></div></div> : <div className="space-y-3">{courses.map(c => <Link className="block rounded-xl border bg-white p-4" key={c.id} href={`/courses/${c.id}`}><strong>{c.title}</strong><p>{c.startDate} {c.startTime}~{c.endTime} · {c.location} · {c.instructor.name}</p></Link>)}{!courses.length && <p>조건에 맞는 일정이 없습니다.</p>}</div>}</div>;
}
