import {
  collection,
  doc,
  addDoc,
  updateDoc,
  serverTimestamp,
  Timestamp,
} from 'firebase/firestore';
import { db } from '../firebase';
import { GoogleGenerativeAI } from '@google/generative-ai';
import type { BlogSchedule, AutoBlogPost, GenerationLog } from './types';
import { getRagDocument, ensureValidFileUri, getImageDownloadUrl } from './rag-manager';
import { generateBlogContent } from './content-generator';

const genAI = new GoogleGenerativeAI(
  process.env.GOOGLE_GENERATIVE_AI_API_KEY || ''
);

/** 사진 URL들을 Gemini Vision으로 분석하여 설명 추출 */
async function analyzeImages(imageUrls: string[]): Promise<string[]> {
  if (!imageUrls.length) return [];

  try {
    const model = genAI.getGenerativeModel({
      model: process.env.GOOGLE_API_MODEL || 'gemini-3-flash-preview',
    });

    const descriptions: string[] = [];
    for (const url of imageUrls.slice(0, 10)) {
      try {
        const response = await fetch(url);
        const buffer = await response.arrayBuffer();
        const base64 = Buffer.from(buffer).toString('base64');
        const mimeType = response.headers.get('content-type') || 'image/jpeg';

        const result = await model.generateContent([
          {
            inlineData: { data: base64, mimeType },
          },
          {
            text: `이 사진을 블로그 글 작성에 활용하기 위해 상세히 분석해주세요.
다음을 포함하여 2~3문장으로 설명:
- 사진에 보이는 주요 대상 (음식, 제품, 공간, 인물 등)
- 색감, 조명, 분위기
- 텍스트가 있다면 읽어서 포함 (메뉴판, 간판, 가격표 등)
- 블로그에서 이 사진을 어떤 맥락으로 사용하면 좋을지

한국어로 간결하게 답변하세요.`,
          },
        ]);

        descriptions.push(result.response.text().trim());
      } catch (e) {
        console.error('[blog-auto] Image analysis failed for:', url, e);
        descriptions.push(`(이미지 분석 실패: ${url})`);
      }
    }

    console.log('[blog-auto] Analyzed', descriptions.length, 'images');
    return descriptions;
  } catch (e) {
    console.error('[blog-auto] Image analysis module error:', e);
    return [];
  }
}

export async function runBlogPipeline(
  schedule: BlogSchedule
): Promise<{
  post: AutoBlogPost;
  log: GenerationLog;
}> {
  const startTime = Date.now();

  try {
    // 1. RAG 문서 URI 수집 + 이미지 다운로드 URL 수집
    const ragFileUris: { uri: string; mimeType: string }[] = [];
    const ragImageUrls: string[] = [];
    for (const docId of schedule.ragDocIds || []) {
      const ragDoc = await getRagDocument(docId);
      if (ragDoc) {
        const validUri = await ensureValidFileUri(ragDoc);
        ragFileUris.push({ uri: validUri, mimeType: ragDoc.mimeType });
        // 이미지 문서면 다운로드 URL도 수집 (블로그 HTML에 삽입용)
        const imgUrl = await getImageDownloadUrl(ragDoc);
        if (imgUrl) ragImageUrls.push(imgUrl);
      }
    }

    // 2. 사진 분석: RAG 이미지 + schedule.imageUrls 모두 분석
    const allImageUrlsForAnalysis = [
      ...ragImageUrls,
      ...(schedule.imageUrls || []),
    ];
    const imageDescriptions = await analyzeImages(allImageUrlsForAnalysis);

    // 3. 콘텐츠 생성 (스킬 + 연구 데이터 + 사진 분석 + 사용자 자료 + 마케팅 컨트롤 반영)
    const allImageUrls = [...ragImageUrls, ...(schedule.imageUrls || [])];
    const marketing = (schedule.targetAudience || schedule.copyFormula || schedule.tone)
      ? {
          targetAudience: schedule.targetAudience,
          copyFormula: schedule.copyFormula,
          tone: schedule.tone,
        }
      : undefined;
    const generated = await generateBlogContent({
      topic: schedule.topic,
      ragFileUris: ragFileUris.length > 0 ? ragFileUris : undefined,
      skillId: schedule.skillId,
      customFields: schedule.customFields,
      imageDescriptions: imageDescriptions.length > 0 ? imageDescriptions : undefined,
      imageUrls: allImageUrls.length > 0 ? allImageUrls : undefined,
      marketing,
    });

    // 3. blog-posts에 저장
    const postRef = await addDoc(collection(db, 'blog-posts'), {
      title: generated.title,
      subtitle: generated.subtitle || '',
      content: generated.content,
      htmlContent: generated.htmlContent,
      excerpt: generated.excerpt,
      tags: generated.tags,
      faqs: generated.faqs || [],
      sources: generated.sources,
      scheduleId: schedule.id,
      isAutoGenerated: true,
      createdAt: serverTimestamp(),
    });

    const post: AutoBlogPost = {
      id: postRef.id,
      title: generated.title,
      content: generated.content,
      htmlContent: generated.htmlContent,
      excerpt: generated.excerpt,
      tags: generated.tags,
      sources: generated.sources,
      scheduleId: schedule.id,
      isAutoGenerated: true,
      createdAt: Timestamp.now(),
    };

    // 4. 생성 로그 저장
    const executionTimeMs = Date.now() - startTime;
    const logRef = await addDoc(collection(db, 'blog-auto-generation-logs'), {
      scheduleId: schedule.id,
      postId: postRef.id,
      status: 'success' as const,
      error: null,
      executionTimeMs,
      createdAt: serverTimestamp(),
    });

    const log: GenerationLog = {
      id: logRef.id,
      scheduleId: schedule.id,
      postId: postRef.id,
      status: 'success',
      error: null,
      executionTimeMs,
      createdAt: Timestamp.now(),
    };

    // 5. schedule.lastRunAt 업데이트
    await updateDoc(doc(db, 'blog-auto-schedules', schedule.id), {
      lastRunAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });

    return { post, log };
  } catch (error: any) {
    // 파이프라인 실패 시 로그 기록
    const executionTimeMs = Date.now() - startTime;
    await addDoc(collection(db, 'blog-auto-generation-logs'), {
      scheduleId: schedule.id,
      postId: '',
      status: 'failed' as const,
      error: error.message || '파이프라인 실패',
      executionTimeMs,
      createdAt: serverTimestamp(),
    });

    throw error;
  }
}
