import { Timestamp } from 'firebase/firestore';
import type { BlogSkillId } from './blog-skills';

// ─── RAG Folder ─────────────────────────────────

export interface RagFolder {
  id: string;
  name: string;
  color: string;              // 폴더 색상 (hex)
  createdAt: Timestamp;
}

// ─── RAG Document ───────────────────────────────

export interface RagDocument {
  id: string;
  fileName: string;
  mimeType: string;
  storagePath: string;        // Firebase Storage 경로 (영구 저장)
  geminiFileUri: string;      // Gemini File API URI (48시간 만료)
  geminiFileExpiry: Timestamp; // URI 만료 시간
  topic: string;
  sizeBytes: number;
  folderId?: string;          // 폴더 ID (미지정 시 루트)
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ─── Schedule ───────────────────────────────────

export type ScheduleFrequency = 'daily' | 'weekly' | 'weekdays';

export type BlogTone = 'friendly' | 'professional' | 'casual' | 'informative' | 'persuasive';
export type BlogCopyFormula = 'auto' | 'AIDA' | 'PAS' | 'BAB' | 'FAB';

export interface BlogSchedule {
  id: string;
  title: string;
  topic: string;
  ragDocIds: string[];
  skillId?: BlogSkillId;      // 블로그 유형 (선택)
  customFields?: Record<string, string>; // 유형별 사용자 입력 자료 (선택)
  imageUrls?: string[];       // 업로드된 사진 URL (선택)
  targetAudience?: string;    // 타겟 오디언스 (마케팅 컨트롤)
  copyFormula?: BlogCopyFormula; // 카피라이팅 공식 오버라이드 (auto = 스킬 기본값)
  tone?: BlogTone;            // 글 톤앤매너
  frequency: ScheduleFrequency;
  time: string;               // "HH:MM"
  dayOfWeek?: number;         // 0-6 (weekly 전용, 0=일요일)
  isActive: boolean;
  lastRunAt: Timestamp | null;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ─── Blog Post (기존 BlogPost 확장) ─────────────

export interface AutoBlogPost {
  id: string;
  title: string;
  content: string;            // 마크다운
  htmlContent: string;        // HTML 변환본
  excerpt: string;
  tags: string[];
  sources: { title: string; url: string }[];
  scheduleId: string | null;
  isAutoGenerated: boolean;
  createdAt: Timestamp;
}

// ─── Generation Log ─────────────────────────────

export type GenerationStatus = 'success' | 'failed';

export interface GenerationLog {
  id: string;
  scheduleId: string;
  postId: string;
  status: GenerationStatus;
  error: string | null;
  executionTimeMs: number;
  createdAt: Timestamp;
}

// ─── Dashboard Stats ────────────────────────────

export interface BlogAutoStats {
  totalPosts: number;
  successCount: number;
  failedCount: number;
  successRate: number;
  thisWeekPosts: number;
  recentLogs: GenerationLog[];
}
